name: Test and Build

on:
  push:                    # すべてのブランチのプッシュで実行
  pull_request:           # すべてのブランチへのプルリクエストで実行

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install all dependencies
      run: |
        npm ci
        cd server && npm ci && cd ..
        
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Lint code
      run: npm run lint
      
    - name: Run tests
      run: npm test || echo "Tests not configured yet"

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Clean and install production dependencies
      run: |
        # Clean existing node_modules
        rm -rf node_modules server/node_modules
        # Install only production dependencies
        npm ci --omit=dev
        cd server && npm ci --omit=dev && cd ..
        
    - name: Install build tools (TypeScript and type definitions)
      run: |
        # Install TypeScript compiler and type definitions for build only
        npm install --no-save typescript @types/node
        cd server && npm install --no-save typescript @types/node && cd ..
        
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Install VSCE
      run: npm install -g @vscode/vsce
      
    - name: Package VSIX
      run: vsce package
      
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: outlinetext-vsix-${{ github.sha }}
        path: '*.vsix'
        retention-days: 30
        
    - name: Show package contents
      run: vsce ls --tree
